/* SalesUncut — Données client */
const SU_DATA = {
  families: [
    { id: 'F1',  name: 'SaaS RH',        icon: '👥' },
    { id: 'F2',  name: 'SaaS Sales CRM', icon: '📊' },
    { id: 'F3',  name: 'Finance',        icon: '💰' },
    { id: 'F4',  name: 'ERP / Ops',      icon: '⚙️' },
    { id: 'F5',  name: 'Cybersécurité',  icon: '🔐' },
    { id: 'F6',  name: 'Sécurité Phys.', icon: '🏢' },
    { id: 'F7',  name: 'Marketing',      icon: '📣' },
    { id: 'F8',  name: 'Énergie',        icon: '⚡' },
    { id: 'F9',  name: 'Télécom',        icon: '📡' },
    { id: 'F10', name: 'Assurance',      icon: '📋' },
  ],
  dimensions: [
    { key: 'accroche',   label: 'Accroche',        max: 16 },
    { key: 'decouverte', label: 'Découverte',      max: 16 },
    { key: 'besoin',     label: 'Créer le besoin', max: 20 },
    { key: 'objections', label: 'Objections',      max: 16 },
    { key: 'valeur',     label: 'Valeur',          max: 16 },
    { key: 'closing',    label: 'Closing',         max: 16 },
  ],
  roles: {
    SDR: { label: 'SDR', full: 'Sales Development Rep' },
    BDR: { label: 'BDR', full: 'Business Development Rep' },
    AE:  { label: 'AE',  full: 'Account Executive' },
    AM:  { label: 'AM',  full: 'Account Manager' },
    KAM: { label: 'KAM', full: 'Key Account Manager' },
    BD:  { label: 'BD',  full: 'Business Developer' },
  },
  candidates: [
    { id:'c001',name:'Lucas Renard',anonymous:false,photo:'G1.png',family:'F2',score:88,level:'gold',location:'Paris',availability:'Immédiat',remote:'Full remote',date:'2026-05-20',
      stats:{accroche:15,decouverte:15,besoin:19,objections:14,valeur:14,closing:11},
      strengths:['Fermeture naturelle','Création de besoin percutante','Gestion pression'],
      weaknesses:['Closing à consolider sous pression','Accroche à personnaliser davantage','Conclusion à formaliser par étapes'],
      role_type:'AE',experience_years:5,experience_level:'Senior',deal_size:'15-50k€',sales_cycle:'6-12 sem.',
      prospection_channels:['Cold call','LinkedIn','Events'],hunting_pct:90,quota_attainment:112,
      sectors_mastered:['SaaS B2B','FinTech','MarTech'],company_size_target:['Scale-up (50-250)','Mid-Market (250-1k)'],
      ote:{fixed:'55-65k',variable:'20-25k',total:'75-90k'},status:'En poste',notice:'3 mois négociable',
      mobility:['Paris IDF','Lyon','Full remote'],
      languages:[{name:'Français',level:'Natif'},{name:'Anglais',level:'C1'}],
      linkedin:'https://www.linkedin.com/in/lucas-renard-demo',cv:'cv-lucas-renard.pdf' },
    { id:'c002',name:'Sara Mourad',anonymous:true,family:'F5',score:83,level:'gold',location:'Lyon',availability:'1 mois',remote:'Hybride',date:'2026-05-18',
      stats:{accroche:14,decouverte:15,besoin:18,objections:13,valeur:13,closing:10},
      strengths:['Maîtrise technique','Crédibilité secteur','Objections complexes'],
      weaknesses:['Closing techniciste à humaniser','Trop de jargon en début appel','Manque de relance après objection prix'],
      role_type:'AE',experience_years:4,experience_level:'Confirmé',deal_size:'20-80k€',sales_cycle:'8-16 sem.',
      prospection_channels:['LinkedIn','Events','Referrals'],hunting_pct:70,quota_attainment:104,
      sectors_mastered:['Cybersécurité','IT services','Banque'],company_size_target:['Mid-Market (250-1k)','ETI (1k-5k)'],
      ote:{fixed:'50-60k',variable:'20-30k',total:'70-90k'},status:'En poste',notice:'2 mois',
      mobility:['Lyon','Genève','Hybride'],
      languages:[{name:'Français',level:'Natif'},{name:'Anglais',level:'C1'},{name:'Arabe',level:'Natif'}],
      linkedin:'',cv:'' },
    { id:'c003',name:'Théo Blanc',anonymous:false,photo:'G2.png',family:'F1',score:78,level:'silver',location:'Bordeaux',availability:'2 mois',remote:'Présentiel ok',date:'2026-05-15',
      stats:{accroche:14,decouverte:14,besoin:16,objections:12,valeur:12,closing:10},
      strengths:['Accroche originale','Empathie forte','Découverte profonde'],
      weaknesses:['Closing trop direct sur prospect frileux','Discovery à approfondir douleur RH','Manque de tunnel de prochaine étape'],
      role_type:'BDR',experience_years:3,experience_level:'Confirmé',deal_size:'8-30k€',sales_cycle:'4-8 sem.',
      prospection_channels:['Cold call','Cold email','LinkedIn'],hunting_pct:95,quota_attainment:98,
      sectors_mastered:['SaaS RH','HR Tech'],company_size_target:['Startup','Scale-up (50-250)'],
      ote:{fixed:'45-55k',variable:'15-22k',total:'60-77k'},status:'En poste',notice:'2 mois',
      mobility:['Bordeaux','Toulouse'],
      languages:[{name:'Français',level:'Natif'},{name:'Anglais',level:'B2'}],
      linkedin:'https://www.linkedin.com/in/theo-blanc-demo',cv:'cv-theo-blanc.pdf' },
    { id:'c004',name:'Camille Faure',anonymous:false,photo:'F1.png',family:'F7',score:75,level:'silver',location:'Nantes',availability:'Immédiat',remote:'Full remote',date:'2026-05-14',
      stats:{accroche:13,decouverte:13,besoin:16,objections:12,valeur:12,closing:9},
      strengths:['Storytelling','Créativité commerciale','Closing doux'],
      weaknesses:['Closing à muscler — trop poli','Quantification ROI imprécise','Tendance à survendre créatif'],
      role_type:'AE',experience_years:3,experience_level:'Confirmé',deal_size:'10-40k€',sales_cycle:'5-10 sem.',
      prospection_channels:['LinkedIn','Content','Events'],hunting_pct:60,quota_attainment:105,
      sectors_mastered:['MarTech','AdTech','E-commerce'],company_size_target:['Startup','Scale-up (50-250)'],
      ote:{fixed:'42-52k',variable:'15-20k',total:'57-72k'},status:'Entre deux postes',notice:'—',
      mobility:['Nantes','Full remote'],
      languages:[{name:'Français',level:'Natif'},{name:'Anglais',level:'C1'},{name:'Espagnol',level:'B2'}],
      linkedin:'https://www.linkedin.com/in/camille-faure-demo',cv:'cv-camille-faure.pdf' },
    { id:'c005',name:'Julien Perrot',anonymous:false,photo:'G3.png',family:'F3',score:72,level:'silver',location:'Paris',availability:'3 mois',remote:'Hybride',date:'2026-05-12',
      stats:{accroche:12,decouverte:14,besoin:15,objections:12,valeur:11,closing:8},
      strengths:['Vocabulaire financier','Structuration du besoin','Patience'],
      weaknesses:['Closing à raccourcir — trop de phases','Accroche trop institutionnelle','Manque de challenge statu quo'],
      role_type:'KAM',experience_years:7,experience_level:'Senior',deal_size:'50-250k€',sales_cycle:'4-9 mois',
      prospection_channels:['Referrals','Events','LinkedIn'],hunting_pct:40,quota_attainment:101,
      sectors_mastered:['Finance','Asset Management','Banque privée'],company_size_target:['ETI (1k-5k)','Grands comptes'],
      ote:{fixed:'55-70k',variable:'30-50k',total:'85-120k'},status:'En poste',notice:'3 mois',
      mobility:['Paris IDF','Hybride'],
      languages:[{name:'Français',level:'Natif'},{name:'Anglais',level:'C2'}],
      linkedin:'https://www.linkedin.com/in/julien-perrot-demo',cv:'cv-julien-perrot.pdf' },
    { id:'c006',name:'Marie Duval',anonymous:true,family:'F8',score:70,level:'silver',location:'Toulouse',availability:'1 mois',remote:'Hybride',date:'2026-05-10',
      stats:{accroche:12,decouverte:13,besoin:15,objections:11,valeur:11,closing:8},
      strengths:['ROI énergétique','Durée de pitch','Reformulation'],
      weaknesses:['Closing à structurer par jalons','Pricing à défendre plus tôt','Manque vocabulaire CapEx/OpEx'],
      role_type:'AE',experience_years:4,experience_level:'Confirmé',deal_size:'30-150k€',sales_cycle:'3-6 mois',
      prospection_channels:['LinkedIn','Events','Salons'],hunting_pct:75,quota_attainment:96,
      sectors_mastered:['Énergie','Industrie','B2B Technique'],company_size_target:['Mid-Market (250-1k)','ETI (1k-5k)'],
      ote:{fixed:'48-58k',variable:'18-25k',total:'66-83k'},status:'En poste',notice:'1 mois',
      mobility:['Toulouse','Bordeaux','Hybride'],
      languages:[{name:'Français',level:'Natif'},{name:'Anglais',level:'B2'}],
      linkedin:'',cv:'' },
    { id:'c007',name:'Nicolas Roy',anonymous:false,photo:'G4.png',family:'F4',score:67,level:'silver',location:'Lille',availability:'Immédiat',remote:'Présentiel ok',date:'2026-05-08',
      stats:{accroche:11,decouverte:12,besoin:14,objections:11,valeur:11,closing:8},
      strengths:['Expertise terrain','Connaissance ERP','Humour contrôlé'],
      weaknesses:['Closing trop technique','Explique produit avant besoin','Manque écoute discovery longue'],
      role_type:'AE',experience_years:4,experience_level:'Confirmé',deal_size:'20-100k€',sales_cycle:'3-6 mois',
      prospection_channels:['Cold call','Events','Salons'],hunting_pct:65,quota_attainment:92,
      sectors_mastered:['ERP','Logistique','Manufacturing'],company_size_target:['Mid-Market (250-1k)','PME (50-250)'],
      ote:{fixed:'40-50k',variable:'15-22k',total:'55-72k'},status:'Démissionnaire',notice:'15 jours',
      mobility:['Lille','Bruxelles','Présentiel'],
      languages:[{name:'Français',level:'Natif'},{name:'Anglais',level:'B2'},{name:'Néerlandais',level:'B1'}],
      linkedin:'https://www.linkedin.com/in/nicolas-roy-demo',cv:'cv-nicolas-roy.pdf' },
    { id:'c008',name:'Élodie Morin',anonymous:false,photo:'F2.png',family:'F9',score:63,level:'silver',location:'Marseille',availability:'2 mois',remote:'Full remote',date:'2026-05-05',
      stats:{accroche:11,decouverte:11,besoin:13,objections:10,valeur:10,closing:8},
      strengths:['Technicité réseau','Écoute active','Reformulation'],
      weaknesses:['Closing : appeler à action plus clairement','Question budget à poser plus tôt','Manque réflexe de relance'],
      role_type:'SDR',experience_years:2,experience_level:'Junior',deal_size:'5-25k€',sales_cycle:'3-6 sem.',
      prospection_channels:['Cold call','Cold email','LinkedIn'],hunting_pct:100,quota_attainment:88,
      sectors_mastered:['Télécom','IT Services'],company_size_target:['Startup','Scale-up (50-250)'],
      ote:{fixed:'38-48k',variable:'10-15k',total:'48-63k'},status:'En poste',notice:'2 mois',
      mobility:['Marseille','Nice','Full remote'],
      languages:[{name:'Français',level:'Natif'},{name:'Anglais',level:'B2'},{name:'Italien',level:'B1'}],
      linkedin:'https://www.linkedin.com/in/elodie-morin-demo',cv:'cv-elodie-morin.pdf' },
    { id:'c009',name:'Antoine Leroy',anonymous:false,photo:'G5.png',family:'F6',score:60,level:'silver',location:'Strasbourg',availability:'Immédiat',remote:'Présentiel ok',date:'2026-05-03',
      stats:{accroche:10,decouverte:11,besoin:13,objections:10,valeur:9,closing:7},
      strengths:['Crédibilité sécurité','Découverte terrain','Présence vocale'],
      weaknesses:['Closing à oser — peur du non','Trop axé peur pas assez bénéfice','Découverte à structurer par questions ouvertes'],
      role_type:'BD',experience_years:2,experience_level:'Junior',deal_size:'10-50k€',sales_cycle:'5-12 sem.',
      prospection_channels:['Cold call','Door-to-door','Events'],hunting_pct:85,quota_attainment:82,
      sectors_mastered:['Sécurité physique','Surveillance','B2B Services'],company_size_target:['PME (50-250)','Mid-Market (250-1k)'],
      ote:{fixed:'38-46k',variable:'10-18k',total:'48-64k'},status:'Entre deux postes',notice:'—',
      mobility:['Strasbourg','Mulhouse','Présentiel'],
      languages:[{name:'Français',level:'Natif'},{name:'Allemand',level:'C1'},{name:'Anglais',level:'B1'}],
      linkedin:'https://www.linkedin.com/in/antoine-leroy-demo',cv:'cv-antoine-leroy.pdf' },
    { id:'c010',name:'Inès Garnier',anonymous:false,photo:'F3.png',family:'F10',score:56,level:'bronze',location:'Rennes',availability:'1 mois',remote:'Hybride',date:'2026-05-01',
      stats:{accroche:10,decouverte:10,besoin:11,objections:9,valeur:9,closing:7},
      strengths:['Connaissances produit','Écoute','Dynamisme'],
      weaknesses:['Closing : oser proposer un RDV directement','Hésitation face objections prix','Discovery écourtée — passe trop vite au pitch'],
      role_type:'SDR',experience_years:1,experience_level:'Junior',deal_size:'2-15k€',sales_cycle:'2-5 sem.',
      prospection_channels:['Cold email','LinkedIn','Inbound'],hunting_pct:80,quota_attainment:78,
      sectors_mastered:['Assurance','InsurTech'],company_size_target:['Startup','PME (50-250)'],
      ote:{fixed:'35-45k',variable:'8-12k',total:'43-57k'},status:'En poste',notice:'1 mois',
      mobility:['Rennes','Nantes','Hybride'],
      languages:[{name:'Français',level:'Natif'},{name:'Anglais',level:'B2'}],
      linkedin:'https://www.linkedin.com/in/ines-garnier-demo',cv:'cv-ines-garnier.pdf' },
  ],
  levels: {
    bronze:{ label:'BRONZE',min:0, max:59, color:'#b08355' },
    silver:{ label:'SILVER',min:60,max:79, color:'#b6c0c4' },
    gold:  { label:'GOLD',  min:80,max:100,color:'#d4a849' },
  },
  viewCounts:{ c001:47,c002:31,c003:28,c004:22,c005:19,c006:17,c007:15,c008:12,c009:9,c010:7 },
  audioMomentsData:{
    c001:[
      {key:'accroche',   moment:'Ouverture du cold call',       ts:'00:42',dur:'28s',featured:false},
      {key:'decouverte', moment:'Qualification du contexte',     ts:'04:12',dur:'35s',featured:true},
      {key:'besoin',     moment:'Construction du besoin latent', ts:'07:55',dur:'40s',featured:false},
      {key:'objections', moment:'Reponse objection prix',        ts:'14:08',dur:'30s',featured:false},
      {key:'valeur',     moment:'Pitch de valeur ROI',           ts:'18:30',dur:'32s',featured:false},
      {key:'closing',    moment:'Demande de signature directe',  ts:'26:10',dur:'22s',featured:false},
    ],
  },
  transcriptData:{
    c001:{
      all:[
        {who:'L',ts:'00:42',text:"Lucas Renard. Je vous appelle parce que vous recrutez 3 AE ce trimestre. Est-ce que le forecasting devient un vrai sujet ?"},
        {who:'P',ts:'01:05',text:"Oui, on a des difficultes de visibilite sur le pipe."},
        {who:'L',ts:'02:14',text:"Vos equipes perdent combien de temps par semaine a ressaisir des donnees entre vos outils ?"},
        {who:'P',ts:'02:31',text:"Honnetement, 4 a 5 heures par commercial, facilement."},
        {who:'L',ts:'02:46',text:"12 commerciaux, 5h, 45 semaines. C'est 2 700 heures perdues par an. On est d'accord ?"},
        {who:'P',ts:'03:02',text:"Je n'avais pas vu les choses comme ca. C'est significatif."},
        {who:'L',ts:'14:08',text:"Vous dites 18 000 euros c'est cher. Mais 2 700 heures a votre taux moyen, c'est un ROI 5x en annee 1."},
        {who:'P',ts:'14:31',text:"Elle ne repond pas vraiment, c'est pour ca qu'on cherche."},
        {who:'L',ts:'18:30',text:"Vos concurrents qui ont adopte ce type d'outil ont gagne 34% de pipeline supplementaire sans recruter."},
        {who:'P',ts:'19:10',text:"Vous avez raison, l'argument tient."},
        {who:'L',ts:'26:10',text:"On se cale 30 minutes avec votre DSI la semaine prochaine, mardi ou jeudi ?"},
        {who:'P',ts:'26:24',text:"Jeudi matin, ca me va."},
      ],
      accroche:[0,1], decouverte:[2,3,4,5], besoin:[4,5], objections:[6,7], valeur:[8,9], closing:[10,11],
    },
  },
  dimensionContent:{
    accroche:{
      key:'accroche',icon:'01',
      headline:"L'Accroche",
      subtitle:"La premiere impression est la seule qui compte.",
      definition:"L'accroche est la fenetre de 15 a 30 secondes pendant laquelle le commercial justifie pourquoi le prospect doit rester en ligne. Un bon hook n'est pas un pitch : c'est une observation contextualisee qui donne envie d'ecouter la suite.",
      stats:[
        {num:"7 sec",  label:"Temps moyen avant qu'un prospect decide de raccrocher ou d'ecouter (Gong.io, 2024)."},
        {num:"+34%",   label:"De taux de conversion sur les calls avec une accroche personnalisee vs generique (RAIN Group)."},
        {num:"1 seule",label:"Contrairement a l'email, la voix ne peut pas etre re-lue. L'accroche se joue en temps reel."},
      ],
      exemple:{
        titre:"De 8% a 31% de conversion en 6 semaines",
        texte:"Une equipe SDR SaaS B2B a remplace son accroche generique par une accroche contextualisee : 'Je vois que vous recrutez 3 AE ce trimestre, ca signifie que le forecasting devient un vrai sujet'. En 6 semaines, le taux cold call vers RDV est passe de 8% a 31%.",
        source:"Etude interne, equipe SDR SaaS B2B, 2025",
      },
      signals:["Personnalisation immediate du contexte prospect","Absence de pitch produit dans les 30 premieres secondes","Question ouverte ou affirmation destabilisante en hook","Tempo vocal adapte","Reference a un evenement declencheur recent"],
      correlations:['decouverte','besoin'],
    },
    decouverte:{
      key:'decouverte',icon:'02',
      headline:"La Decouverte",
      subtitle:"Celui qui pose les questions controle la vente.",
      definition:"La decouverte est la phase d'exploration ou le commercial cartographie la situation reelle du prospect : ses douleurs, ses enjeux, son contexte decisionnel et son niveau d'urgence. Un commercial qui pitche avant de decouvrir est un commercial qui devine.",
      stats:[
        {num:"x2",    label:"Les commerciaux qui posent 11 a 14 questions convertissent 2x plus que ceux qui en posent moins de 6 (Gong.io)."},
        {num:"73%",   label:"Des acheteurs B2B declarent acheter au commercial qui comprend leurs objectifs business, pas leurs besoins produit (Forrester)."},
        {num:"43 min",label:"Duree moyenne d'une decouverte efficace sur un deal mid-market, contre 12 min pour les deals qui echouent."},
      ],
      exemple:{
        titre:"Un deal reouvert par une seule question",
        texte:"Un AE chez un editeur ERP rappelle un prospect froid depuis 3 mois. Il ouvre avec : 'Qu'est-ce qui s'est passe dans votre orga depuis notre dernier echange qui rend ce projet plus ou moins urgent ?'. Le prospect revele un changement de DAF. Le deal redemarre et se signe 6 semaines plus tard.",
        source:"Cas client, editeur ERP mid-market, 2025",
      },
      signals:["Ratio ecoute/parole superieur a 60/40 en faveur du prospect","Questions enchainees sans pitch intermediaire","Reformulation des reponses avant de poursuivre","Exploration du contexte decisionnel","Identification des enjeux business avant les besoins produit"],
      correlations:['accroche','besoin','valeur'],
    },
    besoin:{
      key:'besoin',icon:'03',
      headline:"Creer le Besoin",
      subtitle:"Les meilleurs commerciaux ne repondent pas aux besoins. Ils les creent.",
      definition:"Creer le besoin, c'est transformer une douleur latente en besoin explicite que le prospect formule lui-meme. C'est le coeur de la methode Challenger Sale : le commercial apporte une perspective que le prospect n'avait pas et devient l'architecte de la solution.",
      stats:[
        {num:"87%",label:"Des decisions d'achat B2B complexes demarrent sans RFP defini. Le besoin se construit pendant la vente (CEB/Gartner)."},
        {num:"53%",label:"De l'impact sur la decision d'achat vient de l'experience de vente elle-meme, pas du produit (Challenger Sale)."},
        {num:"x3", label:"Un commercial qui cree le besoin genere 3x plus de deals non sollicites que celui qui repond aux demandes entrantes."},
      ],
      exemple:{
        titre:"Vendre ce que le prospect ne savait pas chercher",
        texte:"Un commercial RH rencontre un DRH qui cherche un outil de suivi des conges. Plutot que de montrer le module conges, il explore : 'Combien de temps vos managers passent-ils a gerer les demandes RH par email ?' La reponse : 6 a 7 heures. Il recadre en cout d'opportunite. La vente passe de 8k a 34k euros.",
        source:"Cas client, editeur SaaS RH, 2025",
      },
      signals:["Reformulation du probleme dans un cadre plus large","Utilisation de donnees pour reveler un angle inconnu","Le prospect dit qu'il n'avait pas vu les choses comme ca","Passage du besoin implicite au besoin explicite","Questions sur le cout de la situation actuelle"],
      correlations:['decouverte','valeur','objections'],
    },
    objections:{
      key:'objections',icon:'04',
      headline:"La Gestion des Objections",
      subtitle:"Une objection n'est pas un non. C'est une demande d'information deguisee.",
      definition:"La gestion des objections est la capacite a recevoir une resistance du prospect sans se defendre ni capituler, mais en transformant cette resistance en levier de progression. Un commercial qui craint les objections les contourne. Un commercial qui les maitrise les cherche.",
      stats:[
        {num:"44%", label:"Des commerciaux abandonnent apres la premiere objection. Seulement 8% relancent 5 fois ou plus et font 80% des ventes (Marketing Donut)."},
        {num:"60%", label:"Des prospects disent non 4 fois avant de dire oui. Le commercial moyen abandonne apres 2 tentatives."},
        {num:"x2.4",label:"Multiplication du taux de closing pour les commerciaux formes a la gestion d'objections structuree vs improvisation (RAIN Group)."},
      ],
      exemple:{
        titre:"Transformer 'c'est trop cher' en signature",
        texte:"Un AE SaaS fait face a l'objection : 'Votre outil coute 3x celui qu'on utilise'. Au lieu de defendre le prix, il repond : '3x plus cher pour quelle valeur comparee ?' Le prospect liste les limitations de son outil. L'AE les quantifie : 47k euros de cout indirect. Le deal a 18k euros se signe la semaine suivante.",
        source:"Cas client, AE SaaS B2B, 2025",
      },
      signals:["Reformulation de l'objection avant de repondre","Absence de defensive ou justification immediate","Questions de clarification pour isoler l'objection reelle","Retour aux enjeux business pour relativiser le frein","Transformation de l'objection en question ouverte"],
      correlations:['valeur','besoin','closing'],
    },
    valeur:{
      key:'valeur',icon:'05',
      headline:"La Valeur",
      subtitle:"Le prix n'est jamais le probleme. L'incapacite a demontrer la valeur l'est.",
      definition:"Articuler la valeur, c'est connecter les capacites du produit aux enjeux business specifiques du prospect en termes de revenus, de couts, de risques ou de temps. Ce n'est pas lister des features. C'est construire un ROI que le prospect peut defendre en interne.",
      stats:[
        {num:"95%", label:"Des acheteurs B2B declarent que le ROI demontrable est le facteur n1 de leur decision (Salesforce State of Sales)."},
        {num:"+30%",label:"D'augmentation du panier moyen pour les commerciaux qui construisent un business case vs ceux qui pitchent des features."},
        {num:"67%", label:"Des deals perdus sur le prix sont en realite perdus sur la valeur non articulee. Le prospect ne pouvait pas justifier en interne."},
      ],
      exemple:{
        titre:"Un business case qui a convaincu le CFO sans RDV",
        texte:"Un commercial cybersecurite fait face a un CFO bloquant. Il construit un one-pager : cout moyen d'une fuite (4.2M euros), probabilite annuelle (12%), cout solution (140k euros), ROI attendu (350%). Le CFO signe sans avoir rencontre le commercial. Le RSSI a vendu en interne grace au business case.",
        source:"Cas client, editeur cybersecurite, 2025",
      },
      signals:["Chiffres concrets avant et apres","Traduction des features en benefices business mesurables","Anticipation de la presentation interne du prospect","References sectorielles comparables","Business case que le prospect peut reutiliser seul"],
      correlations:['besoin','objections','closing'],
    },
    closing:{
      key:'closing',icon:'06',
      headline:"Le Closing",
      subtitle:"Le closing n'est pas une technique. C'est la consequence logique d'une vente bien menee.",
      definition:"Le closing est le moment ou le commercial demande explicitement un engagement. Un closing rate revele souvent un probleme en amont : valeur mal articulee, decideur mal identifie, ou urgence non creee. Le meilleur closing est celui qui ne surprend personne.",
      stats:[
        {num:"63%",   label:"Des meetings se terminent sans prochaine etape claire definie (Hubspot Sales Report)."},
        {num:"50%",   label:"Des commerciaux ne demandent jamais directement la commande pendant un appel de vente."},
        {num:"2-3 sem",label:"Delai moyen gagne quand un commercial demande un closing date des le 1er call vs attendre la fin du cycle."},
      ],
      exemple:{
        titre:"Le closing assume qui debloque un deal a 6 mois",
        texte:"Un AE fait face a un prospect qui repousse depuis 4 mois. Il dit : 'On a valide que le probleme coute 200k euros par an. Notre solution coute 40k euros. Qu'est-ce qui vous empeche de signer ce vendredi ?' Le prospect revele un frein juridique. L'AE propose de contacter le service juridique. Deal signe 10 jours plus tard.",
        source:"Cas client, AE SaaS enterprise, 2025",
      },
      signals:["Demande directe et assumee d'un engagement","Identification du vrai decideur avant le closing","Next step formalise avec date et responsable","Creation d'urgence legitime","Absence d'hesitation ou de sur-qualification tardive"],
      correlations:['valeur','objections','besoin'],
    },
  },
  getLevel(s){return s>=80?'gold':s>=60?'silver':'bronze';},
  getFamilyById(id){return this.families.find(f=>f.id===id)||{name:id,icon:'\u25cf'};},
  getRoleLabel(code){return(this.roles&&this.roles[code])?this.roles[code].full:code;},
  getPercentile(id){const s=[...this.candidates].sort((a,b)=>b.score-a.score);const r=s.findIndex(c=>c.id===id)+1;return r>0?Math.ceil(r/s.length*100):null;},
  getPoolAverageOte(){const v=this.candidates.map(c=>c.ote&&c.ote.total).filter(Boolean).map(s=>{const m=String(s).match(/(\d+)\D+(\d+)/);return m?(parseInt(m[1])+parseInt(m[2]))/2:null;}).filter(Boolean);return v.length?Math.round(v.reduce((a,b)=>a+b,0)/v.length):null;},
  getAudioMoments(id){if(this.audioMomentsData[id])return this.audioMomentsData[id];return this.dimensions.map((d,i)=>({key:d.key,moment:'Extrait '+d.label,ts:String(Math.floor(i*4.5)).padStart(2,'0')+':'+String((i*13)%60).padStart(2,'0'),dur:(25+i*3)+'s',featured:i===1}));},
  getTranscriptLines(id,dim){const d=this.transcriptData[id];if(!d)return[];const idx=d[dim];if(idx&&d.all)return idx.map(i=>d.all[i]).filter(Boolean);return d.all?d.all.slice(0,3):[];},
};
