/* SalesUncut — Données client */
const SU_DATA = {
  families: [
    { id: 'F1',  name: 'SaaS RH',        icon: '👥' },
    { id: 'F2',  name: 'SaaS Sales CRM', icon: '📊' },
    { id: 'F3',  name: 'Finance',        icon: '💰' },
    { id: 'F4',  name: 'ERP / Ops',      icon: '⚙️' },
    { id: 'F5',  name: 'Cybersécurité',  icon: '🔐' },
    { id: 'F6',  name: 'Sécurité Phys.', icon: '🏢' },
    { id: 'F7',  name: 'Marketing',      icon: '📣' },
    { id: 'F8',  name: 'Énergie',        icon: '⚡' },
    { id: 'F9',  name: 'Télécom',        icon: '📡' },
    { id: 'F10', name: 'Assurance',      icon: '📋' },
  ],
  dimensions: [
    { key: 'accroche',   label: 'Accroche',        max: 16 },
    { key: 'decouverte', label: 'Découverte',      max: 16 },
    { key: 'besoin',     label: 'Créer le besoin', max: 20 },
    { key: 'objections', label: 'Objections',      max: 16 },
    { key: 'valeur',     label: 'Valeur',          max: 16 },
    { key: 'closing',    label: 'Closing',         max: 16 },
  ],
  roles: {
    SDR: { label: 'SDR', full: 'Sales Development Rep' },
    BDR: { label: 'BDR', full: 'Business Development Rep' },
    AE:  { label: 'AE',  full: 'Account Executive' },
    AM:  { label: 'AM',  full: 'Account Manager' },
    KAM: { label: 'KAM', full: 'Key Account Manager' },
    BD:  { label: 'BD',  full: 'Business Developer' },
  },
  candidates: [
    { id:'c001',name:'Lucas Renard',anonymous:false,photo:'G1.png',family:'F2',score:88,level:'gold',location:'Paris',availability:'Immédiat',remote:'Full remote',date:'2026-05-20',
      stats:{accroche:15,decouverte:15,besoin:19,objections:14,valeur:14,closing:11},
      strengths:['Fermeture naturelle','Création de besoin percutante','Gestion pression'],
      weaknesses:['Closing à consolider sous pression','Accroche à personnaliser davantage','Conclusion à formaliser par étapes'],
      role_type:'AE',experience_years:5,experience_level:'Senior',deal_size:'15-50k€',sales_cycle:'6-12 sem.',
      prospection_channels:['Cold call','LinkedIn','Events'],hunting_pct:90,quota_attainment:112,
      sectors_mastered:['SaaS B2B','FinTech','MarTech'],company_size_target:['Scale-up (50-250)','Mid-Market (250-1k)'],
      ote:{fixed:'55-65k',variable:'20-25k',total:'75-90k'},status:'En poste',notice:'3 mois négociable',
      mobility:['Paris IDF','Lyon','Full remote'],
      languages:[{name:'Français',level:'Natif'},{name:'Anglais',level:'C1'}],
      linkedin:'https://www.linkedin.com/in/lucas-renard-demo',cv:'cv-lucas-renard.pdf' },
    { id:'c002',name:'Sara Mourad',anonymous:true,family:'F5',score:83,level:'gold',location:'Lyon',availability:'1 mois',remote:'Hybride',date:'2026-05-18',
      stats:{accroche:14,decouverte:15,besoin:18,objections:13,valeur:13,closing:10},
      strengths:['Maîtrise technique','Crédibilité secteur','Objections complexes'],
      weaknesses:['Closing techniciste à humaniser','Trop de jargon en début appel','Manque de relance après objection prix'],
      role_type:'AE',experience_years:4,experience_level:'Confirmé',deal_size:'20-80k€',sales_cycle:'8-16 sem.',
      prospection_channels:['LinkedIn','Events','Referrals'],hunting_pct:70,quota_attainment:104,
      sectors_mastered:['Cybersécurité','IT services','Banque'],company_size_target:['Mid-Market (250-1k)','ETI (1k-5k)'],
      ote:{fixed:'50-60k',variable:'20-30k',total:'70-90k'},status:'En poste',notice:'2 mois',
      mobility:['Lyon','Genève','Hybride'],
      languages:[{name:'Français',level:'Natif'},{name:'Anglais',level:'C1'},{name:'Arabe',level:'Natif'}],
      linkedin:'',cv:'' },
    { id:'c003',name:'Théo Blanc',anonymous:false,photo:'G2.png',family:'F1',score:78,level:'silver',location:'Bordeaux',availability:'2 mois',remote:'Présentiel ok',date:'2026-05-15',
      stats:{accroche:14,decouverte:14,besoin:16,objections:12,valeur:12,closing:10},
      strengths:['Accroche originale','Empathie forte','Découverte profonde'],
      weaknesses:['Closing trop direct sur prospect frileux','Discovery à approfondir douleur RH','Manque de tunnel de prochaine étape'],
      role_type:'BDR',experience_years:3,experience_level:'Confirmé',deal_size:'8-30k€',sales_cycle:'4-8 sem.',
      prospection_channels:['Cold call','Cold email','LinkedIn'],hunting_pct:95,quota_attainment:98,
      sectors_mastered:['SaaS RH','HR Tech'],company_size_target:['Startup','Scale-up (50-250)'],
      ote:{fixed:'45-55k',variable:'15-22k',total:'60-77k'},status:'En poste',notice:'2 mois',
      mobility:['Bordeaux','Toulouse'],
      languages:[{name:'Français',level:'Natif'},{name:'Anglais',level:'B2'}],
      linkedin:'https://www.linkedin.com/in/theo-blanc-demo',cv:'cv-theo-blanc.pdf' },
    { id:'c004',name:'Camille Faure',anonymous:false,photo:'F1.png',family:'F7',score:75,level:'silver',location:'Nantes',availability:'Immédiat',remote:'Full remote',date:'2026-05-14',
      stats:{accroche:13,decouverte:13,besoin:16,objections:12,valeur:12,closing:9},
      strengths:['Storytelling','Créativité commerciale','Closing doux'],
      weaknesses:['Closing à muscler — trop poli','Quantification ROI imprécise','Tendance à survendre créatif'],
      role_type:'AE',experience_years:3,experience_level:'Confirmé',deal_size:'10-40k€',sales_cycle:'5-10 sem.',
      prospection_channels:['LinkedIn','Content','Events'],hunting_pct:60,quota_attainment:105,
      sectors_mastered:['MarTech','AdTech','E-commerce'],company_size_target:['Startup','Scale-up (50-250)'],
      ote:{fixed:'42-52k',variable:'15-20k',total:'57-72k'},status:'Entre deux postes',notice:'—',
      mobility:['Nantes','Full remote'],
      languages:[{name:'Français',level:'Natif'},{name:'Anglais',level:'C1'},{name:'Espagnol',level:'B2'}],
      linkedin:'https://www.linkedin.com/in/camille-faure-demo',cv:'cv-camille-faure.pdf' },
    { id:'c005',name:'Julien Perrot',anonymous:false,photo:'G3.png',family:'F3',score:72,level:'silver',location:'Paris',availability:'3 mois',remote:'Hybride',date:'2026-05-12',
      stats:{accroche:12,decouverte:14,besoin:15,objections:12,valeur:11,closing:8},
      strengths:['Vocabulaire financier','Structuration du besoin','Patience'],
      weaknesses:['Closing à raccourcir — trop de phases','Accroche trop institutionnelle','Manque de challenge statu quo'],
      role_type:'KAM',experience_years:7,experience_level:'Senior',deal_size:'50-250k€',sales_cycle:'4-9 mois',
      prospection_channels:['Referrals','Events','LinkedIn'],hunting_pct:40,quota_attainment:101,
      sectors_mastered:['Finance','Asset Management','Banque privée'],company_size_target:['ETI (1k-5k)','Grands comptes'],
      ote:{fixed:'55-70k',variable:'30-50k',total:'85-120k'},status:'En poste',notice:'3 mois',
      mobility:['Paris IDF','Hybride'],
      languages:[{name:'Français',level:'Natif'},{name:'Anglais',level:'C2'}],
      linkedin:'https://www.linkedin.com/in/julien-perrot-demo',cv:'cv-julien-perrot.pdf' },
    { id:'c006',name:'Marie Duval',anonymous:true,family:'F8',score:70,level:'silver',location:'Toulouse',availability:'1 mois',remote:'Hybride',date:'2026-05-10',
      stats:{accroche:12,decouverte:13,besoin:15,objections:11,valeur:11,closing:8},
      strengths:['ROI énergétique','Durée de pitch','Reformulation'],
      weaknesses:['Closing à structurer par jalons','Pricing à défendre plus tôt','Manque vocabulaire CapEx/OpEx'],
      role_type:'AE',experience_years:4,experience_level:'Confirmé',deal_size:'30-150k€',sales_cycle:'3-6 mois',
      prospection_channels:['LinkedIn','Events','Salons'],hunting_pct:75,quota_attainment:96,
      sectors_mastered:['Énergie','Industrie','B2B Technique'],company_size_target:['Mid-Market (250-1k)','ETI (1k-5k)'],
      ote:{fixed:'48-58k',variable:'18-25k',total:'66-83k'},status:'En poste',notice:'1 mois',
      mobility:['Toulouse','Bordeaux','Hybride'],
      languages:[{name:'Français',level:'Natif'},{name:'Anglais',level:'B2'}],
      linkedin:'',cv:'' },
    { id:'c007',name:'Nicolas Roy',anonymous:false,photo:'G4.png',family:'F4',score:67,level:'silver',location:'Lille',availability:'Immédiat',remote:'Présentiel ok',date:'2026-05-08',
      stats:{accroche:11,decouverte:12,besoin:14,objections:11,valeur:11,closing:8},
      strengths:['Expertise terrain','Connaissance ERP','Humour contrôlé'],
      weaknesses:['Closing trop technique','Explique produit avant besoin','Manque écoute discovery longue'],
      role_type:'AE',experience_years:4,experience_level:'Confirmé',deal_size:'20-100k€',sales_cycle:'3-6 mois',
      prospection_channels:['Cold call','Events','Salons'],hunting_pct:65,quota_attainment:92,
      sectors_mastered:['ERP','Logistique','Manufacturing'],company_size_target:['Mid-Market (250-1k)','PME (50-250)'],
      ote:{fixed:'40-50k',variable:'15-22k',total:'55-72k'},status:'Démissionnaire',notice:'15 jours',
      mobility:['Lille','Bruxelles','Présentiel'],
      languages:[{name:'Français',level:'Natif'},{name:'Anglais',level:'B2'},{name:'Néerlandais',level:'B1'}],
      linkedin:'https://www.linkedin.com/in/nicolas-roy-demo',cv:'cv-nicolas-roy.pdf' },
    { id:'c008',name:'Élodie Morin',anonymous:false,photo:'F2.png',family:'F9',score:63,level:'silver',location:'Marseille',availability:'2 mois',remote:'Full remote',date:'2026-05-05',
      stats:{accroche:11,decouverte:11,besoin:13,objections:10,valeur:10,closing:8},
      strengths:['Technicité réseau','Écoute active','Reformulation'],
      weaknesses:['Closing : appeler à action plus clairement','Question budget à poser plus tôt','Manque réflexe de relance'],
      role_type:'SDR',experience_years:2,experience_level:'Junior',deal_size:'5-25k€',sales_cycle:'3-6 sem.',
      prospection_channels:['Cold call','Cold email','LinkedIn'],hunting_pct:100,quota_attainment:88,
      sectors_mastered:['Télécom','IT Services'],company_size_target:['Startup','Scale-up (50-250)'],
      ote:{fixed:'38-48k',variable:'10-15k',total:'48-63k'},status:'En poste',notice:'2 mois',
      mobility:['Marseille','Nice','Full remote'],
      languages:[{name:'Français',level:'Natif'},{name:'Anglais',level:'B2'},{name:'Italien',level:'B1'}],
      linkedin:'https://www.linkedin.com/in/elodie-morin-demo',cv:'cv-elodie-morin.pdf' },
    { id:'c009',name:'Antoine Leroy',anonymous:false,photo:'G5.png',family:'F6',score:60,level:'silver',location:'Strasbourg',availability:'Immédiat',remote:'Présentiel ok',date:'2026-05-03',
      stats:{accroche:10,decouverte:11,besoin:13,objections:10,valeur:9,closing:7},
      strengths:['Crédibilité sécurité','Découverte terrain','Présence vocale'],
      weaknesses:['Closing à oser — peur du non','Trop axé peur pas assez bénéfice','Découverte à structurer par questions ouvertes'],
      role_type:'BD',experience_years:2,experience_level:'Junior',deal_size:'10-50k€',sales_cycle:'5-12 sem.',
      prospection_channels:['Cold call','Door-to-door','Events'],hunting_pct:85,quota_attainment:82,
      sectors_mastered:['Sécurité physique','Surveillance','B2B Services'],company_size_target:['PME (50-250)','Mid-Market (250-1k)'],
      ote:{fixed:'38-46k',variable:'10-18k',total:'48-64k'},status:'Entre deux postes',notice:'—',
      mobility:['Strasbourg','Mulhouse','Présentiel'],
      languages:[{name:'Français',level:'Natif'},{name:'Allemand',level:'C1'},{name:'Anglais',level:'B1'}],
      linkedin:'https://www.linkedin.com/in/antoine-leroy-demo',cv:'cv-antoine-leroy.pdf' },
    { id:'c010',name:'Inès Garnier',anonymous:false,photo:'F3.png',family:'F10',score:56,level:'bronze',location:'Rennes',availability:'1 mois',remote:'Hybride',date:'2026-05-01',
      stats:{accroche:10,decouverte:10,besoin:11,objections:9,valeur:9,closing:7},
      strengths:['Connaissances produit','Écoute','Dynamisme'],
      weaknesses:['Closing : oser proposer un RDV directement','Hésitation face objections prix','Discovery écourtée — passe trop vite au pitch'],
      role_type:'SDR',experience_years:1,experience_level:'Junior',deal_size:'2-15k€',sales_cycle:'2-5 sem.',
      prospection_channels:['Cold email','LinkedIn','Inbound'],hunting_pct:80,quota_attainment:78,
      sectors_mastered:['Assurance','InsurTech'],company_size_target:['Startup','PME (50-250)'],
      ote:{fixed:'35-45k',variable:'8-12k',total:'43-57k'},status:'En poste',notice:'1 mois',
      mobility:['Rennes','Nantes','Hybride'],
      languages:[{name:'Français',level:'Natif'},{name:'Anglais',level:'B2'}],
      linkedin:'https://www.linkedin.com/in/ines-garnier-demo',cv:'cv-ines-garnier.pdf' },
  ],
  levels: {
    bronze:{ label:'BRONZE',min:0, max:59, color:'#b08355' },
    silver:{ label:'SILVER',min:60,max:79, color:'#b6c0c4' },
    gold:  { label:'GOLD',  min:80,max:100,color:'#d4a849' },
  },
  viewCounts:{ c001:47,c002:31,c003:28,c004:22,c005:19,c006:17,c007:15,c008:12,c009:9,c010:7 },

  /* ============ AUDIO MOMENTS PAR CANDIDAT ============ */
  audioMomentsData:{
    c001:[
      {key:'accroche',   moment:'Ouverture du cold call',        ts:'00:42',dur:'28s',featured:false},
      {key:'decouverte', moment:'Qualification du contexte',      ts:'04:12',dur:'35s',featured:true},
      {key:'besoin',     moment:'Construction du besoin latent',  ts:'07:55',dur:'40s',featured:false},
      {key:'objections', moment:'Reponse objection prix',         ts:'14:08',dur:'30s',featured:false},
      {key:'valeur',     moment:'Pitch de valeur ROI',            ts:'18:30',dur:'32s',featured:false},
      {key:'closing',    moment:'Demande de signature directe',   ts:'26:10',dur:'22s',featured:false},
    ],
    c002:[
      {key:'accroche',   moment:'Accroche cyber contextualisee',  ts:'00:38',dur:'25s',featured:false},
      {key:'decouverte', moment:'Exploration surface d attaque',   ts:'05:20',dur:'38s',featured:true},
      {key:'besoin',     moment:'Quantification du risque',        ts:'10:40',dur:'35s',featured:false},
      {key:'objections', moment:'Objection cout vs couverture',   ts:'15:15',dur:'32s',featured:false},
      {key:'valeur',     moment:'ROI securite argumente',         ts:'19:30',dur:'30s',featured:false},
      {key:'closing',    moment:'Proposition de POC structure',   ts:'23:00',dur:'28s',featured:false},
    ],
    c003:[
      {key:'accroche',   moment:'Hook sur temps admin RH',        ts:'00:45',dur:'26s',featured:false},
      {key:'decouverte', moment:'Exploration des douleurs RH',    ts:'04:30',dur:'40s',featured:true},
      {key:'besoin',     moment:'Recadrage en cout opportunite',  ts:'09:10',dur:'35s',featured:false},
      {key:'objections', moment:'Objection budget serree',        ts:'16:00',dur:'28s',featured:false},
      {key:'valeur',     moment:'Impact sur retention talents',   ts:'20:15',dur:'30s',featured:false},
      {key:'closing',    moment:'Proposition de demo RH',         ts:'25:00',dur:'22s',featured:false},
    ],
    c004:[
      {key:'accroche',   moment:'Observation site web prospect',  ts:'00:52',dur:'28s',featured:false},
      {key:'decouverte', moment:'Diagnostic baisse conversion',   ts:'04:00',dur:'38s',featured:true},
      {key:'besoin',     moment:'Recadrage probleme landing',     ts:'09:30',dur:'35s',featured:false},
      {key:'objections', moment:'Objection resultats prouvables', ts:'17:00',dur:'30s',featured:false},
      {key:'valeur',     moment:'Benchmark secteur e-commerce',  ts:'21:00',dur:'32s',featured:false},
      {key:'closing',    moment:'Proposition audit gratuit',      ts:'25:00',dur:'20s',featured:false},
    ],
    c005:[
      {key:'accroche',   moment:'Accroche cloture mensuelle',     ts:'00:55',dur:'26s',featured:false},
      {key:'decouverte', moment:'Cartographie process Excel',     ts:'05:10',dur:'40s',featured:true},
      {key:'besoin',     moment:'Calcul cout ressources cloture', ts:'11:00',dur:'38s',featured:false},
      {key:'objections', moment:'Resistance au changement equipe',ts:'18:30',dur:'32s',featured:false},
      {key:'valeur',     moment:'ROI reduction delai cloture',    ts:'22:00',dur:'30s',featured:false},
      {key:'closing',    moment:'Proposition pilote 2 entites',  ts:'26:00',dur:'24s',featured:false},
    ],
    c006:[
      {key:'accroche',   moment:'Stat pertes energetiques',       ts:'00:48',dur:'26s',featured:false},
      {key:'decouverte', moment:'Audit obsolete et nouveaux sites',ts:'04:30',dur:'38s',featured:true},
      {key:'besoin',     moment:'Absence visibilite ligne par ligne',ts:'10:20',dur:'35s',featured:false},
      {key:'objections', moment:'Demande de proposition ecrite',  ts:'19:00',dur:'28s',featured:false},
      {key:'valeur',     moment:'Cas client reduction 22 pourcent',ts:'23:00',dur:'30s',featured:false},
      {key:'closing',    moment:'Proposition demo sur site',      ts:'27:00',dur:'22s',featured:false},
    ],
    c007:[
      {key:'accroche',   moment:'Diagnostic saturation ERP',      ts:'00:50',dur:'26s',featured:false},
      {key:'decouverte', moment:'Identification modules critiques',ts:'04:00',dur:'38s',featured:true},
      {key:'besoin',     moment:'Calcul perte CA sur ruptures',   ts:'08:30',dur:'35s',featured:false},
      {key:'objections', moment:'Necessite validation DG',        ts:'16:00',dur:'28s',featured:false},
      {key:'valeur',     moment:'Demo projection donnees live',   ts:'20:00',dur:'32s',featured:false},
      {key:'closing',    moment:'Proposition session de 2 heures',ts:'23:00',dur:'20s',featured:false},
    ],
    c008:[
      {key:'accroche',   moment:'Probleme connectivite site secondaire',ts:'00:42',dur:'24s',featured:false},
      {key:'decouverte', moment:'Frequence et duree des coupures', ts:'04:15',dur:'38s',featured:true},
      {key:'besoin',     moment:'Impact production non calcule',  ts:'09:00',dur:'35s',featured:false},
      {key:'objections', moment:'SLA operateur actuel insuffisant',ts:'17:30',dur:'28s',featured:false},
      {key:'valeur',     moment:'SLA 99.95 avec backup 4G',      ts:'22:00',dur:'30s',featured:false},
      {key:'closing',    moment:'Proposition audit infrastructure',ts:'24:00',dur:'20s',featured:false},
    ],
    c009:[
      {key:'accroche',   moment:'Contexte intrusions zone industrielle',ts:'00:55',dur:'26s',featured:false},
      {key:'decouverte', moment:'Tentative intrusion recente',    ts:'04:45',dur:'38s',featured:true},
      {key:'besoin',     moment:'Delai detection inconnu',        ts:'11:00',dur:'35s',featured:false},
      {key:'objections', moment:'Validation comptable necessaire',ts:'18:30',dur:'28s',featured:false},
      {key:'valeur',     moment:'Detection 30 secondes et alerte',ts:'22:00',dur:'30s',featured:false},
      {key:'closing',    moment:'Proposition visite du site',     ts:'24:00',dur:'20s',featured:false},
    ],
    c010:[
      {key:'accroche',   moment:'Salaries en deplacement international',ts:'00:38',dur:'24s',featured:false},
      {key:'decouverte', moment:'Zones de couverture incertaines', ts:'04:20',dur:'36s',featured:true},
      {key:'besoin',     moment:'Incident hospitalisation Asie',  ts:'09:30',dur:'35s',featured:false},
      {key:'objections', moment:'Demande de documentation',       ts:'18:00',dur:'26s',featured:false},
      {key:'valeur',     moment:'Cout incident non assure 200k',  ts:'21:00',dur:'28s',featured:false},
      {key:'closing',    moment:'Proposition point la semaine prochaine',ts:'23:00',dur:'20s',featured:false},
    ],
  },

  /* ============ TRANSCRIPTS PAR CANDIDAT (10/10) ============ */
  transcriptData:{
    c001:{all:[{who:'L',ts:'00:42',text:"Lucas Renard. Je vous appelle parce que vous recrutez 3 AE ce trimestre. Est-ce que le forecasting devient un vrai sujet ?"},{who:'P',ts:'01:05',text:"Oui, on a des difficultes de visibilite sur le pipe."},{who:'L',ts:'02:14',text:"Vos equipes perdent combien de temps par semaine a ressaisir des donnees entre vos outils ?"},{who:'P',ts:'02:31',text:"Honnetement, 4 a 5 heures par commercial, facilement."},{who:'L',ts:'02:46',text:"12 commerciaux, 5h, 45 semaines. C'est 2 700 heures perdues par an. On est d'accord ?"},{who:'P',ts:'03:02',text:"Je n'avais pas vu les choses comme ca. C'est significatif."},{who:'L',ts:'14:08',text:"Vous dites 18 000 euros c'est cher. Mais 2 700 heures a votre taux moyen, c'est un ROI 5x en annee 1."},{who:'P',ts:'14:31',text:"Elle ne repond pas vraiment, c'est pour ca qu'on cherche."},{who:'L',ts:'18:30',text:"Vos concurrents qui ont adopte ce type d'outil ont gagne 34 pourcent de pipeline supplementaire sans recruter."},{who:'P',ts:'19:10',text:"Vous avez raison, l'argument tient."},{who:'L',ts:'26:10',text:"On se cale 30 minutes avec votre DSI la semaine prochaine, mardi ou jeudi ?"},{who:'P',ts:'26:24',text:"Jeudi matin, ca me va."}],accroche:[0,1],decouverte:[2,3,4,5],besoin:[4,5],objections:[6,7],valeur:[8,9],closing:[10,11]},
    c002:{all:[{who:'L',ts:'00:38',text:"Bonjour. Je vous appelle parce que le secteur bancaire est la cible numero un des ransomwares en 2026. Vous avez eu des alertes recemment ?"},{who:'P',ts:'01:02',text:"Oui, deux tentatives de phishing qui ont failli passer. Notre equipe SOC est reduite."},{who:'L',ts:'05:20',text:"Avec une equipe SOC reduite pour une banque de votre taille, vous couvrez combien de pourcent de votre surface d'attaque en detection ?"},{who:'P',ts:'05:45',text:"On estime environ 60 pourcent. Le reste on le decouvre apres coup."},{who:'L',ts:'10:40',text:"40 pourcent de surface non couverte dans un contexte bancaire, ca represente quel risque reglementaire pour vous ?"},{who:'P',ts:'11:08',text:"Un risque DORA significant. On a une inspection en septembre."},{who:'L',ts:'15:15',text:"Votre solution actuelle coute combien ? Je vous pose la question parce que Shieldwork vous donne 94 pourcent de couverture pour 95 000 euros annuels."},{who:'P',ts:'15:42',text:"On est a 80 000. La difference de 15 000 euros pour 34 pourcent de couverture supplementaire, c'est un argument que je peux porter."},{who:'L',ts:'19:30',text:"Les banques qui ont deploye notre SOC augmente ont passe leurs audits DORA sans reserve. Je vous envoie 3 cas secteur ce soir."},{who:'P',ts:'19:55',text:"Oui, envoyez-moi ca. Mon RSSI est ouvert a evaluer."},{who:'L',ts:'23:00',text:"On organise un POC de 30 jours avec votre equipe. Je vous propose de caler ca avec votre RSSI la semaine prochaine ?"},{who:'P',ts:'23:18',text:"Oui, envoyez-moi une proposition avec les modalites du POC."}],accroche:[0,1],decouverte:[2,3],besoin:[4,5],objections:[6,7],valeur:[8,9],closing:[10,11]},
    c003:{all:[{who:'L',ts:'00:45',text:"Bonjour, Theo Blanc chez Huma. Les DRH que je rencontre passent 60 pourcent de leur temps sur de l'admin RH. C'est votre cas aussi ?"},{who:'P',ts:'01:10',text:"Honnêtement oui. On est a 450 salaries et l'onboarding seul nous prend enormement de temps."},{who:'L',ts:'04:30',text:"Cet onboarding, c'est combien de personnes mobilisees et combien de semaines par recrue ?"},{who:'P',ts:'04:55',text:"Deux personnes RH pendant 3 semaines en moyenne par nouvelle recrue. On recrute 80 personnes par an."},{who:'L',ts:'09:10',text:"80 recrutements fois 3 semaines fois 2 personnes, c'est 480 semaines-personnes par an uniquement sur l'onboarding. Si vous recuperiez 40 pourcent de ce temps, qu'est-ce que vos RH feraient avec ?"},{who:'P',ts:'09:35',text:"On se concentrerait sur le developpement des talents et la reduction du turnover. C'est notre vrai role."},{who:'L',ts:'16:00',text:"Je comprends que le budget est un frein. Mais combien vous coute un depart non anticipe en recrutement et perte de productivite ?"},{who:'P',ts:'16:28',text:"On estime 15 000 euros par depart. On en a eu 12 l'an dernier qu'on aurait pu eviter."},{who:'L',ts:'20:15',text:"180 000 euros de turnover evitable contre une solution a 24 000 euros annuels. Le calcul est rapide. Des clients similaires ont reduit leur turnover de 28 pourcent en 18 mois."},{who:'P',ts:'20:42',text:"C'est un argument que je peux porter a ma direction."},{who:'L',ts:'25:00',text:"On se cale un demo avec votre DRH et votre DSI la semaine prochaine ?"},{who:'P',ts:'25:18',text:"Je vois comment j'organise ca et je vous rappelle en fin de semaine."}],accroche:[0,1],decouverte:[2,3],besoin:[4,5],objections:[6,7],valeur:[8,9],closing:[10,11]},
    c004:{all:[{who:'L',ts:'00:52',text:"Bonjour, Camille Faure de GrowthLab. J'ai regarde votre site ce matin et vos landing pages ont un probleme de conversion. Vous en etes consciente ?"},{who:'P',ts:'01:18',text:"Oui, notre taux de conversion est en baisse depuis 3 mois. C'est notre preoccupation principale."},{who:'L',ts:'04:00',text:"Cette baisse, c'est quoi selon vous la cause principale ? L'acquisition, la landing, ou le tunnel de conversion ?"},{who:'P',ts:'04:22',text:"On pense que c'est l'acquisition. Notre cout par lead a double."},{who:'L',ts:'09:30',text:"Et si le probleme n'etait pas l'acquisition mais la retention sur la landing ? Vos concurrents ont refait leur UX et leur message. Vous n'avez pas retouche vos pages depuis combien de temps ?"},{who:'P',ts:'09:55',text:"8 mois. Vous avez peut-etre raison, on n'a pas analyse ce point."},{who:'L',ts:'17:00',text:"Vous voulez un chiffre concret avant de nous engager. Je comprends. On travaille avec 3 marques e-commerce dans votre segment. En moyenne, 2.3 points de conversion en 6 semaines. Sur votre volume, ca fait quoi ?"},{who:'P',ts:'17:28',text:"Sur notre volume, facilement 200 000 euros de CA supplementaire si c'est vrai."},{who:'L',ts:'21:00',text:"Ce n'est pas une promesse, c'est une moyenne observee. Je vous montre les cas detailles et vous jugez si votre situation est comparable."},{who:'P',ts:'21:25',text:"D'accord, envoyez-moi ca."},{who:'L',ts:'25:00',text:"Je vous propose un audit gratuit de vos landing pages cette semaine. On se fixe un point vendredi pour les resultats ?"},{who:'P',ts:'25:18',text:"Vendredi ca me va. Envoyez-moi une invitation."}],accroche:[0,1],decouverte:[2,3],besoin:[4,5],objections:[6,7],valeur:[8,9],closing:[10,11]},
    c005:{all:[{who:'L',ts:'00:55',text:"Bonjour, Julien Perrot de Clearflow. Nous travaillons avec des fonds de votre taille sur la consolidation de reporting. Votre cloture mensuelle, elle prend combien de jours ?"},{who:'P',ts:'01:20',text:"8 jours. C'est trop long pour notre comite de gestion qui veut les chiffres sous 5 jours."},{who:'L',ts:'05:10',text:"Ces 8 jours, c'est principalement du Excel ou vous avez deja un outil de consolidation ?"},{who:'P',ts:'05:32',text:"Principalement Excel. On a 12 entites a consolider avec des devises differentes."},{who:'L',ts:'11:00',text:"12 entites sous Excel multi-devises, c'est combien de personnes mobilisees pendant ces 8 jours ?"},{who:'P',ts:'11:18',text:"4 personnes a temps plein. Et ca genere des erreurs qu'on passe ensuite du temps a corriger."},{who:'L',ts:'18:30',text:"Le changement d'outil dans une equipe finance, c'est un risque reel. C'est pour ca qu'on commence toujours par un pilote sur 2 entites pendant 90 jours avant tout engagement."},{who:'P',ts:'18:58',text:"Un pilote, ca change tout. Ca reduit le risque de maniere significative."},{who:'L',ts:'22:00',text:"Vos 4 ressources sur 8 jours fois 12 mois representent environ 200 000 euros en couts humains annuels. Notre solution ramene ca a 3 jours. C'est 60 pourcent de ce cout."},{who:'P',ts:'22:30',text:"Le ROI est evident. Je dois en parler a mon associe gerant."},{who:'L',ts:'26:00',text:"Quand pouvez-vous en parler a votre associe ? Je propose qu'on se retrouve tous les trois la semaine prochaine."},{who:'P',ts:'26:22',text:"Donnez-moi 2 semaines. Je reviens vers vous."}],accroche:[0,1],decouverte:[2,3],besoin:[4,5],objections:[6,7],valeur:[8,9],closing:[10,11]},
    c006:{all:[{who:'L',ts:'00:48',text:"Bonjour. Les entreprises industrielles de votre taille perdent en moyenne 18 pourcent sur leur facture energetique par manque de visibilite en temps reel. Vous avez deja audite vos consommations ?"},{who:'P',ts:'01:15',text:"On a fait un audit il y a 2 ans. Depuis on n'a pas eu le temps de s'y remettre."},{who:'L',ts:'04:30',text:"En 2 ans, vos lignes de production ont change. Cet audit est encore representatif de votre situation actuelle selon vous ?"},{who:'P',ts:'04:52',text:"Probablement pas. On a installe 3 nouvelles lignes depuis."},{who:'L',ts:'10:20',text:"Ces 3 nouvelles lignes, elles sont monitorees comment ? Vous avez une visibilite sur leur consommation individuelle ?"},{who:'P',ts:'10:45',text:"Non, on voit seulement la consommation globale du site. Impossible d'identifier les derives ligne par ligne."},{who:'L',ts:'19:00',text:"Un concurrent dans votre secteur a reduit sa facture de 22 pourcent en 4 mois avec notre monitoring. Sur votre facture annuelle, ca represente combien ?"},{who:'P',ts:'19:28',text:"Sur 2 millions annuels, ca ferait 440 000 euros. C'est significatif. C'est quoi votre approche exactement ?"},{who:'L',ts:'23:00',text:"On installe nos capteurs en 48h sans interruption de production. Envoyez-moi une proposition d'abord pour que je valide le concept avec mon equipe."},{who:'P',ts:'23:25',text:"Je vous prepare ca cette semaine avec un chiffrage pour votre site."},{who:'L',ts:'27:00',text:"Je vous propose une demo sur site la semaine prochaine pour voir concretement comment ca fonctionne ?"},{who:'P',ts:'27:20',text:"Oui, ca m'interesse. Proposez-moi des creneaux."}],accroche:[0,1],decouverte:[2,3],besoin:[4,5],objections:[6,7],valeur:[8,9],closing:[10,11]},
    c007:{all:[{who:'L',ts:'00:50',text:"Nicolas Roy de Factorly. On travaille avec des PME industrielles en forte croissance qui saturent leur ERP actuel. Vous avez des signes de saturation sur le votre ?"},{who:'P',ts:'01:15',text:"Oui, nos temps de traitement ont triple depuis qu'on a passe 200 salaries. La gestion de stock est chaotique."},{who:'L',ts:'04:00',text:"Ce ralentissement, il touche quels modules principalement ? La production, la logistique, les commandes ?"},{who:'P',ts:'04:22',text:"Surtout la gestion de stock et les commandes. On a des ecarts permanents qui generent des ruptures."},{who:'L',ts:'08:30',text:"Ces ecarts de stock, ca vous coute combien en commandes perdues ou en retards de livraison ?"},{who:'P',ts:'08:52',text:"On estime 5 pourcent du CA perdu en ruptures. Sur 8 millions de CA, c'est 400 000 euros."},{who:'L',ts:'16:00',text:"Pour vous montrer concretement ce que Factorly change sur votre type de situation, je vous propose de projeter vos donnees de stock dans notre outil. Ca prend 2 heures. Quand etes-vous dispo ?"},{who:'P',ts:'16:25',text:"La semaine prochaine. Mais je dois d'abord en parler a mon directeur general."},{who:'L',ts:'20:00',text:"Parfait. Les PME industrielles similaires que nous accompagnons recuperent en moyenne 3 a 4 points de CA en 6 mois. Sur 8 millions, c'est 240 000 a 320 000 euros."},{who:'P',ts:'20:30',text:"Si c'est vrai, le ROI est evident. Je parle a mon DG demain."},{who:'L',ts:'23:00',text:"Je vous propose qu'on se cale une session demo avec votre DG et moi la semaine prochaine. Mardi ou mercredi ?"},{who:'P',ts:'23:22',text:"Mercredi apres-midi, ca devrait aller."}],accroche:[0,1],decouverte:[2,3],besoin:[4,5],objections:[6,7],valeur:[8,9],closing:[10,11]},
    c008:{all:[{who:'L',ts:'00:42',text:"Bonjour, Elodie Morin de Connecta Pro. On voit beaucoup d'entreprises de votre secteur avec des problemes de connectivite sur leurs sites secondaires. C'est le cas chez vous ?"},{who:'P',ts:'01:08',text:"Effectivement, notre site de Rouen a des coupures regulieres. C'est un vrai probleme operationnel."},{who:'L',ts:'04:15',text:"Ces coupures, elles ont quelle frequence et quelle duree en moyenne ?"},{who:'P',ts:'04:38',text:"A peu pres une fois par semaine, 20 a 30 minutes. Ca impacte notre ligne de production."},{who:'L',ts:'09:00',text:"20 a 30 minutes d'arret par semaine sur un site de production, ca represente combien en perte de productivite ? Vous avez calcule ?"},{who:'P',ts:'09:25',text:"On n'a pas calcule precisement. Mais c'est clairement significatif sur notre resultat."},{who:'L',ts:'17:30',text:"Votre operateur actuel, quel SLA vous garantit-il ?"},{who:'P',ts:'17:48',text:"99.5 pourcent theoriquement. Mais en pratique on est en dessous."},{who:'L',ts:'22:00',text:"On propose un SLA de 99.95 pourcent avec un backup 4G automatique qui prend le relais en moins de 10 secondes. Pour votre site de Rouen, c'est 350 euros par mois."},{who:'P',ts:'22:25',text:"C'est dans notre budget. Je transmettrai a Sebastien qui gere l'infra pour valider."},{who:'L',ts:'24:00',text:"On peut faire un audit de votre infrastructure Rouen cette semaine. Je vous propose jeudi matin ?"},{who:'P',ts:'24:18',text:"Oui, envoyez-moi les details. Je transmets a Sebastien."}],accroche:[0,1],decouverte:[2,3],besoin:[4,5],objections:[6,7],valeur:[8,9],closing:[10,11]},
    c009:{all:[{who:'L',ts:'00:55',text:"Bonjour, Antoine Leroy de VigilHome Pro. On constate une augmentation des intrusions dans les zones industrielles de votre region cet ete. Vous avez eu des incidents sur votre site ?"},{who:'P',ts:'01:22',text:"Oui, une tentative d'intrusion il y a 3 mois. Ca nous a fait realiser qu'on n'etait pas assez proteges."},{who:'L',ts:'04:45',text:"Votre systeme actuel, il couvre quoi exactement ? Le perimetrique uniquement ou aussi l'interieur du site ?"},{who:'P',ts:'05:08',text:"Surtout perimetrique. L'interieur du site est peu monitore."},{who:'L',ts:'11:00',text:"Si quelqu'un franchit votre perimetre et entre dans le site, vous etes alertes en combien de temps ?"},{who:'P',ts:'11:25',text:"Honnêtement, on ne sait pas. C'est exactement ce qui nous preoccupe depuis l'incident."},{who:'L',ts:'18:30',text:"VigilHome vous donne une detection en moins de 30 secondes avec alerte sur smartphone et intervention automatique du centre de telesurveillance. Pour un site de votre taille, c'est 850 euros par mois."},{who:'P',ts:'18:55',text:"C'est dans notre budget. Je dois juste valider avec mon comptable que ca rentre dans l'enveloppe securite."},{who:'L',ts:'22:00',text:"Nos clients dans votre secteur ont tous obtenu une reduction de leur prime d'assurance apres installation, ce qui couvre souvent 30 a 40 pourcent du cout mensuel."},{who:'P',ts:'22:28',text:"Ah, ca je ne savais pas. Ca change le calcul."},{who:'L',ts:'24:00',text:"Je vous propose une visite du site la semaine prochaine pour vous faire une offre sur mesure. Lundi ou mardi ?"},{who:'P',ts:'24:18',text:"Appelez-moi lundi matin pour caler ca."}],accroche:[0,1],decouverte:[2,3],besoin:[4,5],objections:[6,7],valeur:[8,9],closing:[10,11]},
    c010:{all:[{who:'L',ts:'00:38',text:"Bonjour, Ines Garnier de Covertis. On travaille avec des entreprises de votre secteur sur la protection de leurs salaries en deplacement international. Vous avez des collaborateurs qui voyagent regulierement ?"},{who:'P',ts:'01:05',text:"Oui, une trentaine de personnes qui se deplacent en Europe et parfois hors Europe pour des missions."},{who:'L',ts:'04:20',text:"Ces deplacements hors Europe, ils sont couverts par votre assurance actuelle ou il y a des zones d'ombre ?"},{who:'P',ts:'04:45',text:"Bonne question. Je ne suis pas certain. Notre contrat date de 4 ans."},{who:'L',ts:'09:30',text:"Un contrat de 4 ans sur ce type de couverture, il y a probablement des zones non couvertes qui ont evolue avec la reglementation internationale. Vous avez eu des incidents de sante a l'etranger ?"},{who:'P',ts:'09:55',text:"Oui, un collaborateur hospitalise en Asie l'an dernier. Ca a ete tres complique a gerer et tres couteux."},{who:'L',ts:'18:00',text:"Ce type d'incident non anticipe peut couter entre 50 000 et 200 000 euros hors assurance. Notre formule voyageurs couvre 195 pays pour 45 euros par mois et par personne."},{who:'P',ts:'18:25',text:"C'est raisonnable. Envoyez-moi une documentation detaillee."},{who:'L',ts:'21:00',text:"Pour 30 personnes, on est a 1 350 euros par mois. Versus un incident non assure a 100 000 euros. Je vous envoie ca et 2 cas clients similaires."},{who:'P',ts:'21:25',text:"D'accord. Ca m'aide a cadrer la conversation avec ma direction."},{who:'L',ts:'23:00',text:"Je vous envoie ca aujourd'hui et on se cale un point la semaine prochaine pour repondre a vos questions ?"},{who:'P',ts:'23:18',text:"D'accord. Appelez-moi mercredi matin."}],accroche:[0,1],decouverte:[2,3],besoin:[4,5],objections:[6,7],valeur:[8,9],closing:[10,11]},
  },

  /* ============ CONTENU EDITORIAL PAR DIMENSION ============ */
  dimensionContent:{
    accroche:{key:'accroche',icon:'01',headline:"L'Accroche",subtitle:"La premiere impression est la seule qui compte.",definition:"L'accroche est la fenetre de 15 a 30 secondes pendant laquelle le commercial justifie pourquoi le prospect doit rester en ligne. Un bon hook n'est pas un pitch : c'est une observation contextualisee qui donne envie d'ecouter la suite.",stats:[{num:"7 sec",label:"Temps moyen avant qu'un prospect decide de raccrocher ou d'ecouter (Gong.io, 2024)."},{num:"+34%",label:"De taux de conversion sur les calls avec une accroche personnalisee vs generique (RAIN Group)."},{num:"1 seule",label:"Contrairement a l'email, la voix ne peut pas etre re-lue. L'accroche se joue en temps reel."}],exemple:{titre:"De 8% a 31% de conversion en 6 semaines",texte:"Une equipe SDR SaaS B2B a remplace son accroche generique par une accroche contextualisee : 'Je vois que vous recrutez 3 AE ce trimestre, ca signifie que le forecasting devient un vrai sujet'. En 6 semaines, le taux cold call vers RDV est passe de 8% a 31%.",source:"Etude interne, equipe SDR SaaS B2B, 2025"},signals:["Personnalisation immediate du contexte prospect","Absence de pitch produit dans les 30 premieres secondes","Question ouverte ou affirmation destabilisante en hook","Tempo vocal adapte","Reference a un evenement declencheur recent"],correlations:['decouverte','besoin']},
    decouverte:{key:'decouverte',icon:'02',headline:"La Decouverte",subtitle:"Celui qui pose les questions controle la vente.",definition:"La decouverte est la phase d'exploration ou le commercial cartographie la situation reelle du prospect : ses douleurs, ses enjeux, son contexte decisionnel et son niveau d'urgence. Un commercial qui pitche avant de decouvrir est un commercial qui devine.",stats:[{num:"x2",label:"Les commerciaux qui posent 11 a 14 questions convertissent 2x plus que ceux qui en posent moins de 6 (Gong.io)."},{num:"73%",label:"Des acheteurs B2B declarent acheter au commercial qui comprend leurs objectifs business, pas leurs besoins produit (Forrester)."},{num:"43 min",label:"Duree moyenne d'une decouverte efficace sur un deal mid-market, contre 12 min pour les deals qui echouent."}],exemple:{titre:"Un deal reouvert par une seule question",texte:"Un AE chez un editeur ERP rappelle un prospect froid depuis 3 mois. Il ouvre avec : 'Qu'est-ce qui s'est passe dans votre orga depuis notre dernier echange qui rend ce projet plus ou moins urgent ?'. Le prospect revele un changement de DAF. Le deal redemarre et se signe 6 semaines plus tard.",source:"Cas client, editeur ERP mid-market, 2025"},signals:["Ratio ecoute/parole superieur a 60/40 en faveur du prospect","Questions enchainees sans pitch intermediaire","Reformulation des reponses avant de poursuivre","Exploration du contexte decisionnel","Identification des enjeux business avant les besoins produit"],correlations:['accroche','besoin','valeur']},
    besoin:{key:'besoin',icon:'03',headline:"Creer le Besoin",subtitle:"Les meilleurs commerciaux ne repondent pas aux besoins. Ils les creent.",definition:"Creer le besoin, c'est transformer une douleur latente en besoin explicite que le prospect formule lui-meme. C'est le coeur de la methode Challenger Sale : le commercial apporte une perspective que le prospect n'avait pas et devient l'architecte de la solution.",stats:[{num:"87%",label:"Des decisions d'achat B2B complexes demarrent sans RFP defini. Le besoin se construit pendant la vente (CEB/Gartner)."},{num:"53%",label:"De l'impact sur la decision d'achat vient de l'experience de vente elle-meme, pas du produit (Challenger Sale)."},{num:"x3",label:"Un commercial qui cree le besoin genere 3x plus de deals non sollicites que celui qui repond aux demandes entrantes."}],exemple:{titre:"Vendre ce que le prospect ne savait pas chercher",texte:"Un commercial RH rencontre un DRH qui cherche un outil de suivi des conges. Plutot que de montrer le module conges, il explore : 'Combien de temps vos managers passent-ils a gerer les demandes RH par email ?' La reponse : 6 a 7 heures. Il recadre en cout d'opportunite. La vente passe de 8k a 34k euros.",source:"Cas client, editeur SaaS RH, 2025"},signals:["Reformulation du probleme dans un cadre plus large","Utilisation de donnees pour reveler un angle inconnu","Le prospect dit qu'il n'avait pas vu les choses comme ca","Passage du besoin implicite au besoin explicite","Questions sur le cout de la situation actuelle"],correlations:['decouverte','valeur','objections']},
    objections:{key:'objections',icon:'04',headline:"La Gestion des Objections",subtitle:"Une objection n'est pas un non. C'est une demande d'information deguisee.",definition:"La gestion des objections est la capacite a recevoir une resistance du prospect sans se defendre ni capituler, mais en transformant cette resistance en levier de progression. Un commercial qui craint les objections les contourne. Un commercial qui les maitrise les cherche.",stats:[{num:"44%",label:"Des commerciaux abandonnent apres la premiere objection. Seulement 8% relancent 5 fois ou plus et font 80% des ventes (Marketing Donut)."},{num:"60%",label:"Des prospects disent non 4 fois avant de dire oui. Le commercial moyen abandonne apres 2 tentatives."},{num:"x2.4",label:"Multiplication du taux de closing pour les commerciaux formes a la gestion d'objections structuree vs improvisation (RAIN Group)."}],exemple:{titre:"Transformer 'c'est trop cher' en signature",texte:"Un AE SaaS fait face a l'objection : 'Votre outil coute 3x celui qu'on utilise'. Au lieu de defendre le prix, il repond : '3x plus cher pour quelle valeur comparee ?' Le prospect liste les limitations de son outil. L'AE les quantifie : 47k euros de cout indirect. Le deal a 18k euros se signe la semaine suivante.",source:"Cas client, AE SaaS B2B, 2025"},signals:["Reformulation de l'objection avant de repondre","Absence de defensive ou justification immediate","Questions de clarification pour isoler l'objection reelle","Retour aux enjeux business pour relativiser le frein","Transformation de l'objection en question ouverte"],correlations:['valeur','besoin','closing']},
    valeur:{key:'valeur',icon:'05',headline:"La Valeur",subtitle:"Le prix n'est jamais le probleme. L'incapacite a demontrer la valeur l'est.",definition:"Articuler la valeur, c'est connecter les capacites du produit aux enjeux business specifiques du prospect en termes de revenus, de couts, de risques ou de temps. Ce n'est pas lister des features. C'est construire un ROI que le prospect peut defendre en interne.",stats:[{num:"95%",label:"Des acheteurs B2B declarent que le ROI demontrable est le facteur n1 de leur decision (Salesforce State of Sales)."},{num:"+30%",label:"D'augmentation du panier moyen pour les commerciaux qui construisent un business case vs ceux qui pitchent des features."},{num:"67%",label:"Des deals perdus sur le prix sont en realite perdus sur la valeur non articulee. Le prospect ne pouvait pas justifier en interne."}],exemple:{titre:"Un business case qui a convaincu le CFO sans RDV",texte:"Un commercial cybersecurite fait face a un CFO bloquant. Il construit un one-pager : cout moyen d'une fuite (4.2M euros), probabilite annuelle (12%), cout solution (140k euros), ROI attendu (350%). Le CFO signe sans avoir rencontre le commercial. Le RSSI a vendu en interne grace au business case.",source:"Cas client, editeur cybersecurite, 2025"},signals:["Chiffres concrets avant et apres","Traduction des features en benefices business mesurables","Anticipation de la presentation interne du prospect","References sectorielles comparables","Business case que le prospect peut reutiliser seul"],correlations:['besoin','objections','closing']},
    closing:{key:'closing',icon:'06',headline:"Le Closing",subtitle:"Le closing n'est pas une technique. C'est la consequence logique d'une vente bien menee.",definition:"Le closing est le moment ou le commercial demande explicitement un engagement. Un closing rate revele souvent un probleme en amont : valeur mal articulee, decideur mal identifie, ou urgence non creee. Le meilleur closing est celui qui ne surprend personne.",stats:[{num:"63%",label:"Des meetings se terminent sans prochaine etape claire definie (Hubspot Sales Report)."},{num:"50%",label:"Des commerciaux ne demandent jamais directement la commande pendant un appel de vente."},{num:"2-3 sem",label:"Delai moyen gagne quand un commercial demande un closing date des le 1er call vs attendre la fin du cycle."}],exemple:{titre:"Le closing assume qui debloque un deal a 6 mois",texte:"Un AE fait face a un prospect qui repousse depuis 4 mois. Il dit : 'On a valide que le probleme coute 200k euros par an. Notre solution coute 40k euros. Qu'est-ce qui vous empeche de signer ce vendredi ?' Le prospect revele un frein juridique. L'AE propose de contacter le service juridique. Deal signe 10 jours plus tard.",source:"Cas client, AE SaaS enterprise, 2025"},signals:["Demande directe et assumee d'un engagement","Identification du vrai decideur avant le closing","Next step formalise avec date et responsable","Creation d'urgence legitime","Absence d'hesitation ou de sur-qualification tardive"],correlations:['valeur','objections','besoin']},
  },

  /* ============ ANALYSE DIMENSIONNELLE PAR CANDIDAT ============ */
  dimAnalysis:{
    c001:{
      accroche:   "Lucas ouvre avec une observation business précise — il cite le recrutement en cours pour justifier l'appel. L'accroche est calibrée et non générique, ce qui force le prospect à confirmer le contexte avant même le pitch.",
      decouverte: "Il enchaîne les questions quantitatives avec un rythme soutenu : heures perdues, nombre de commerciaux, semaines de travail. La découverte est structurée en entonnoir et aboutit à un calcul que le prospect valide lui-même.",
      besoin:     "Point fort absolu : Lucas transforme une inefficacité opérationnelle en coût annuel chiffré (2 700 heures) sans forcer. Le prospect dit naturellement 'je n'avais pas vu les choses comme ça' — signe que le besoin a été créé, pas révélé.",
      objections: "Face à l'objection prix, il ne défend pas le tarif — il redirige vers le ROI calculé en découverte. La réponse est fluide et non défensive, ce qui démontre une gestion mature de la résistance prix.",
      valeur:     "Il articule la valeur avec une référence sectorielle (+34% de pipeline) et un chiffre d'impact direct. La valeur est présentée comme observable, pas comme une promesse, ce qui crédibilise l'argument.",
      closing:    "Le closing est direct mais pas brusque — il propose un format concret (30 min avec le DSI) et deux créneaux. C'est un closing en entonnoir qui réduit la friction tout en forçant une décision.",
    },
    c002:{
      accroche:   "Sara contextualise avec une statistique sectorielle (ransomwares, secteur bancaire), ce qui ancre l'appel dans l'actualité. L'accroche est pertinente mais légèrement technique pour une première ouverture.",
      decouverte: "Elle explore la surface d'attaque avec précision et identifie le gap de couverture (40%). La découverte est très solide sur le plan technique mais s'appuie peu sur les enjeux financiers — elle parle davantage en termes IT qu'en termes de risque business.",
      besoin:     "Sara fait le lien entre la couverture incomplète et le risque réglementaire DORA — c'est un excellent angle de création de besoin. L'inspection en septembre crée une urgence naturelle qu'elle exploite sans forcer.",
      objections: "Elle gère l'objection coût avec un différentiel chiffré (15k€ pour 34% de couverture supplémentaire) et laisse le prospect faire le calcul lui-même. Très efficace, mais la réponse manque légèrement de chaleur.",
      valeur:     "Les cas sectoriels (banques ayant passé DORA sans réserve) sont très convaincants. Sara propose de les envoyer ce soir, créant un next step immédiat. La valeur est bien articulée sur le plan compliance.",
      closing:    "Le closing propose un POC de 30 jours, ce qui réduit le risque perçu pour le prospect. C'est un bon choix tactique pour un environnement bancaire prudent, même si l'engagement reste conditionné à une proposition écrite.",
    },
    c003:{
      accroche:   "Théo démarre avec une statistique forte (60% du temps en admin RH) qui provoque immédiatement une confirmation. L'accroche est empathique et ne sonne pas commercial, ce qui favorise l'ouverture du dialogue.",
      decouverte: "La découverte est approfondie et chiffrée — il calcule avec le prospect le volume de ressources mobilisées. L'approche est méthodique mais pourrait explorer davantage les enjeux stratégiques (turnover, rétention) en amont.",
      besoin:     "Théo crée le besoin en transformant le problème opérationnel en opportunité de recentrage sur la valeur RH. La question 'qu'est-ce que vos RH feraient avec ce temps ?' est excellente — elle fait formuler le bénéfice par le prospect.",
      objections: "Il rebondit sur l'objection budget en quantifiant le turnover évitable (15k€ × 12 départs). La réponse est solide, mais il aurait pu challenger plus tôt la perception du coût avant d'arriver à l'objection prix.",
      valeur:     "Théo connecte la solution à un ROI concret (180k€ de turnover vs 24k€ de solution) et cite un cas similaire. La valeur est bien articulée, mais le chiffre de -28% de turnover aurait besoin d'une source pour renforcer la crédibilité.",
      closing:    "Il propose un demo avec DRH et DSI, ce qui est pertinent pour un achat SaaS RH. Mais il accepte trop facilement un 'je vous rappelle' sans proposer de date précise — le next step reste flou à la sortie du call.",
    },
    c004:{
      accroche:   "Camille ouvre avec une observation directe sur le site du prospect, démontrant une préparation réelle. L'accroche est personnalisée et crée une asymétrie d'information favorable, même si la formulation est légèrement abrupte.",
      decouverte: "Sa découverte identifie la bonne douleur (baisse de conversion) mais progresse trop vite dans le diagnostic sans laisser le prospect développer. Elle pose de bonnes questions mais coupe légèrement le flux de réponse.",
      besoin:     "Camille recadre efficacement le problème en questionnant l'hypothèse du prospect (acquisition vs landing). C'est un beau mouvement Challenger, mais l'angle aurait gagné à être appuyé par une donnée sectorielle pour renforcer la conviction.",
      objections: "Elle gère l'objection preuve avec un benchmark concret (+2,3 pts de conversion) et un impact calculé pour le prospect. La réponse est bien structurée, mais présentée comme une moyenne, ce qui peut manquer d'impact tranchant.",
      valeur:     "Camille propose de montrer des cas comparables plutôt que de promettre — approche consultative qui inspire confiance. Mais elle manque d'un chiffre d'impact propre au prospect pour rendre la valeur plus tangible et immédiate.",
      closing:    "L'audit gratuit est une bonne proposition de closing, mais le call se termine sur 'envoyez-moi une invitation' sans qualification plus poussée. Le closing est doux, cohérent avec son style, mais le next step manque de structure.",
    },
    c005:{
      accroche:   "Julien ouvre avec une question directe sur la durée de clôture, montrant une bonne connaissance du métier. L'accroche est professionnelle mais institutionnelle — elle manque d'un élément de surprise pour créer une vraie rupture.",
      decouverte: "La découverte cartographie bien les outils et les entités, mais progresse lentement. Julien pose de bonnes questions mais laisse des silences qui pourraient être exploités pour approfondir les enjeux décisionnels.",
      besoin:     "Le calcul des coûts humains (4 personnes × 8 jours × 12 mois) est solide. Mais Julien attend trop longtemps pour y arriver — ce calcul en découverte aurait créé le besoin bien plus tôt dans la conversation.",
      objections: "Il gère l'objection changement avec une approche pilote très pertinente pour un environnement financier conservateur. C'est la meilleure réponse du call — sobre, rassurante, sans survente.",
      valeur:     "Le calcul ROI est bien construit, mais Julien le présente au moment où le prospect révèle qu'il doit consulter un co-décideur. La valeur aurait dû être articulée plus tôt pour inclure l'associé gérant dans la réflexion.",
      closing:    "Il propose un next step trilogue intelligent pour un deal co-géré. Mais il accepte un '2 semaines' sans date précise ni urgence créée — le closing manque de structure pour un deal à long cycle.",
    },
    c006:{
      accroche:   "Marie ouvre avec un chiffre d'impact sectoriel (18% de pertes) qui crée immédiatement de la pertinence. L'accroche est bien calibrée pour un interlocuteur industriel et déclenche naturellement la confirmation du prospect.",
      decouverte: "Elle identifie que l'audit existant est obsolète (2 ans, 3 nouvelles lignes) — excellent angle qui crée une urgence implicite. Mais la découverte reste en surface sur les enjeux financiers liés aux dérives de consommation.",
      besoin:     "Marie fait émerger le manque de visibilité ligne par ligne de manière naturelle. Mais elle aurait pu quantifier immédiatement le coût de cette absence de visibilité pour ancrer le besoin dans un chiffre business concret.",
      objections: "Elle répond à la demande de proposition avec un cas client chiffré qui ramène le prospect à l'impact financier. La gestion est efficace mais elle aurait pu proposer un next step plus concret avant d'envoyer une proposition.",
      valeur:     "Le cas client est bien choisi et la projection (440k€ sur 2M€ de facture) est calculée avec le prospect. La valeur est tangible et crédible, ce qui démontre une bonne maîtrise de l'argumentaire ROI énergétique.",
      closing:    "Le closing demo sur site est pertinent pour un achat industriel. Mais Marie accepte la proposition écrite sans challenger le timing — la demo aurait dû être proposée avant la proposition pour créer de l'adhésion.",
    },
    c007:{
      accroche:   "Nicolas cible bien la saturation ERP comme déclencheur — c'est pertinent et terrain. Mais l'accroche reste générique et manque d'un élément de personnalisation sur le prospect spécifique pour créer une vraie asymétrie.",
      decouverte: "Il identifie rapidement les modules critiques mais passe à l'impact financier un peu tôt, avant d'avoir pleinement cartographié le contexte décisionnel. La découverte est efficace mais légèrement court-circuitée.",
      besoin:     "Le calcul des 400k€ de CA perdu en ruptures est fort — et chiffré par le prospect lui-même. Mais Nicolas arrive à ce moment après avoir déjà présenté son outil, ce qui affaiblit l'effet de création de besoin.",
      objections: "L'objection validation DG est gérée par une proposition de session demo conjointe. Mais Nicolas n'explore pas pourquoi le DG n'est pas déjà dans la boucle — une occasion manquée de comprendre le cycle décisionnel.",
      valeur:     "Les chiffres présentés (3-4 pts de CA) sont convaincants mais présentés rapidement, sans laisser le prospect s'approprier le calcul. La valeur est articulée mais pas co-construite, ce qui réduit son pouvoir de conviction interne.",
      closing:    "Nicolas obtient un créneau concret (mercredi après-midi) — c'est un bon résultat. Mais la session est conditionnée à la validation du DG sans que ce point soit sécurisé. Le next step est réel mais fragile.",
    },
    c008:{
      accroche:   "Élodie ouvre avec un problème sectoriel générique (connectivité sur sites secondaires) qui déclenche la confirmation du prospect. L'accroche est correcte mais manque de personnalisation pour créer une vraie asymétrie d'information.",
      decouverte: "Elle collecte les données de fréquence et durée des coupures, mais ne pousse pas le prospect à quantifier l'impact production. Elle pose la question et accepte 'c'est significatif' sans ancrer un chiffre précis.",
      besoin:     "Le besoin reste implicite — elle ne parvient pas à faire formuler par le prospect l'impact financier exact des coupures. La douleur est identifiée mais jamais quantifiée, ce qui fragilise tout le reste de la conversation.",
      objections: "Elle utilise l'objection SLA comme transition vers son offre — la réponse est fluide. Mais elle ne challenge pas le fait que le prospect soit sous le SLA théorique sans avoir engagé de recours, ce qui aurait renforcé le besoin.",
      valeur:     "La valeur (SLA 99.95%, backup 4G, 350€/mois) est claire et bien présentée. Mais sans chiffre d'impact préalable sur les coupures, la valeur paraît théorique plutôt qu'ancrée dans la réalité opérationnelle du prospect.",
      closing:    "Élodie propose un audit avec un créneau précis (jeudi matin) — c'est son point fort. Le closing est direct et sans hésitation, même si elle aurait dû qualifier davantage la décision de 'Sébastien' avant de partir sur un audit.",
    },
    c009:{
      accroche:   "Antoine contextualise avec les données d'intrusions régionales — pertinent et terrain. Mais l'accroche repose sur la peur, ce qui peut créer un réflexe défensif. Un angle bénéfice aurait équilibré l'ouverture.",
      decouverte: "Il explore le système actuel avec méthode et identifie le point aveugle (intérieur du site peu monitoré). La découverte est propre mais manque de questions sur le contexte décisionnel et le budget sécurité disponible.",
      besoin:     "La question sur le délai de détection est excellente — elle fait réaliser au prospect lui-même son angle mort. C'est le meilleur moment de création de besoin du call : sobre, naturel et efficace.",
      objections: "Antoine gère l'objection comptable avec l'argument des primes d'assurance — une information que le prospect ne connaissait pas, ce qui crée une vraie valeur ajoutée. La réponse est pertinente mais arrive un peu tard.",
      valeur:     "La valeur technique (30 secondes, télésurveillance) est bien présentée mais la connexion à l'impact business reste faible. Il aurait pu quantifier le coût d'un incident non détecté pour ancrer la valeur dans un chiffre concret.",
      closing:    "Le closing 'appelez-moi lundi matin' est trop passif — le prospect contrôle le next step. Antoine aurait dû proposer lui-même une date et heure précises pour garder la main sur le suivi.",
    },
    c010:{
      accroche:   "Inès pose une question d'ouverture pertinente (déplacements internationaux) mais trop générique. L'accroche manque d'un élément de personnalisation ou d'une statistique qui créerait une urgence immédiate chez le prospect.",
      decouverte: "Elle identifie l'angle clé (contrat de 4 ans potentiellement obsolète) mais passe rapidement. La découverte aurait gagné à explorer les zones géographiques couvertes et les incidents passés avant d'aborder l'Asie.",
      besoin:     "L'incident en Asie est un excellent ancrage — Inès l'utilise pour créer le besoin, mais aurait pu le laisser développer davantage par le prospect pour que la douleur soit formulée dans ses propres mots, avec plus d'impact.",
      objections: "Face à la demande de documentation, Inès envoie les informations sans challenger le timing ni qualifier le processus décisionnel interne. C'est une réponse safe mais passive qui allonge le cycle de vente.",
      valeur:     "Le calcul (1 350€/mois vs 100k€ d'incident non assuré) est bien structuré. Mais Inès le présente rapidement sans laisser le prospect réagir — ce qui réduit l'impact et la co-construction de la valeur.",
      closing:    "Le closing 'appelez-moi mercredi matin' est accepté passivement sans qualifier le prochain rendez-vous. Inès n'identifie pas les autres décideurs impliqués, ce qui fragilise la suite du cycle.",
    },
  },

  /* ============ METHODES ============ */
  getLevel(s){return s>=80?'gold':s>=60?'silver':'bronze';},
  getFamilyById(id){return this.families.find(f=>f.id===id)||{name:id,icon:'\u25cf'};},
  getRoleLabel(code){return(this.roles&&this.roles[code])?this.roles[code].full:code;},
  getPercentile(id){const s=[...this.candidates].sort((a,b)=>b.score-a.score);const r=s.findIndex(c=>c.id===id)+1;return r>0?Math.ceil(r/s.length*100):null;},
  getPoolAverageOte(){const v=this.candidates.map(c=>c.ote&&c.ote.total).filter(Boolean).map(s=>{const m=String(s).match(/(\d+)\D+(\d+)/);return m?(parseInt(m[1])+parseInt(m[2]))/2:null;}).filter(Boolean);return v.length?Math.round(v.reduce((a,b)=>a+b,0)/v.length):null;},
  getAudioMoments(id){if(this.audioMomentsData[id])return this.audioMomentsData[id];return this.dimensions.map((d,i)=>({key:d.key,moment:'Extrait '+d.label,ts:String(Math.floor(i*4.5)).padStart(2,'0')+':'+String((i*13)%60).padStart(2,'0'),dur:(25+i*3)+'s',featured:i===1}));},
  getTranscriptLines(id,dim){
    const d=this.transcriptData[id];
    if(!d)return[];
    if(dim==='all')return d.all||[];
    const idx=d[dim];
    if(idx&&d.all)return idx.map(i=>d.all[i]).filter(Boolean);
    return d.all?d.all.slice(0,3):[];
  },
};
